# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lincoln', '0003_auto_20170423_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='pothole',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=50, null=True),
        ),
    ]
