# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lincoln', '0005_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='violation',
        ),
        migrations.RemoveField(
            model_name='construction',
            name='contacts',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Violation',
        ),
    ]
